Update flake env (#165)
The current environment has a rustc that is too old:

```
error: package `clap v4.5.0` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.72.0
Either upgrade to rustc 1.74 or newer, or use
cargo update -p clap@4.5.0 --precise ver
where `ver` is the latest version of `clap` supporting rustc 1.72.0
```