Fix broken gzip step in release workflow.
The workflow fails with:

```
gzip: target/x86_64-unknown-linux-musl/release/git-nomad has 1 other link  -- unchanged
Error: Process completed with exit code 2.
```

That's because `gzip` has a symlink check enabled by default, `--force`
overrides it.