Use clap ArgGroup to represent purge options
This lets clap know about the conflict between these two options, which
improves help and error messages.

Before:

```
$ cargo run -q purge
Error: Must specify --all or --host
```

After:

```
$ cargo run -q purge
error: The following required arguments were not provided:
    <--all|--host <host>...>

USAGE:
    git-nomad purge --git <git> --user <user> <--all|--host <host>...>

For more information try --help
```